# BIG DIVE Intesa 3
## Numpy
by Stefania Delprete, TOP-IX  
stefania.delprete@top-ix.org 

https://www.linkedin.com/in/astrastefania   
https://twitter.com/astrastefania  

---

## NumFOCUS

The mission of NumFOCUS, 501(c)3 non-profit organization, is to promote sustainable high-level programming languages, open code development, and reproducible scientific research.  
https://www.numfocus.org  
https://pydata.org

---

## NumPy

http://www.numpy.org   
https://github.com/numpy/numpy


In [1]:
import numpy as np

In [2]:
np.__version__

'1.16.0'

---
## Importing some maths

In [3]:
np.sqrt(144)

12.0

In [4]:
np.pi

3.141592653589793

In [5]:
np.sin(np.pi)

1.2246467991473532e-16

### NumPy array, unidimensional

In [6]:
heights_list = [175, 180, 168, 190, 175, 164, 189, 173, 171.23] # list
heights_np = np.array(heights_list) # NumPy array

In [7]:
heights_list, type(heights_list)

([175, 180, 168, 190, 175, 164, 189, 173, 171.23], list)

In [10]:
heights_list * 2

[175,
 180,
 168,
 190,
 175,
 164,
 189,
 173,
 171.23,
 175,
 180,
 168,
 190,
 175,
 164,
 189,
 173,
 171.23]

In [11]:
heights_np, type(heights_np)

(array([175.  , 180.  , 168.  , 190.  , 175.  , 164.  , 189.  , 173.  ,
        171.23]), numpy.ndarray)

In [12]:
heights_np * 2 # vector multiplication with a scalar

array([350.  , 360.  , 336.  , 380.  , 350.  , 328.  , 378.  , 346.  ,
       342.46])

In [13]:
heights_np / 2 # vector division with a scalar

array([87.5  , 90.   , 84.   , 95.   , 87.5  , 82.   , 94.5  , 86.5  ,
       85.615])

In [14]:
heights_np + 100

array([275.  , 280.  , 268.  , 290.  , 275.  , 264.  , 289.  , 273.  ,
       271.23])

In [15]:
np.sort(heights_np)

array([164.  , 168.  , 171.23, 173.  , 175.  , 175.  , 180.  , 189.  ,
       190.  ])

### Some statistics

In [16]:
mean = np.mean(heights_np)
mean

176.13666666666666

In [17]:
np.round(mean)

176.0

In [18]:
np.median(heights_np)

175.0

In [19]:
np.sum(heights_np)

1585.23

### Generating unidimentional arrays

In [20]:
np.zeros(9) # array of 9 zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
nine_ones = np.ones(9) # array of 9 ones
nine_ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [22]:
np.append(nine_ones,4) # add 4 at the end

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 4.])

In [23]:
np.insert(nine_ones,8,3.14) # insert at position 8, np.insert(np-array,index,value)

array([1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 3.14, 1.  ])

In [30]:
range(0,10,1)

range(0, 10)

In [24]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [25]:
np.arange(0,15,3)

array([ 0,  3,  6,  9, 12])

In [26]:
rep_pattern = np.tile([3.14,42,2.99], 4) # repeating the pattern 4 times
rep_pattern

array([ 3.14, 42.  ,  2.99,  3.14, 42.  ,  2.99,  3.14, 42.  ,  2.99,
        3.14, 42.  ,  2.99])

In [27]:
np.unique([1,2,1,1,2]) # unique values

array([1, 2])

In [28]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [31]:
np.linspace(50, 1000, 15)

array([  50.        ,  117.85714286,  185.71428571,  253.57142857,
        321.42857143,  389.28571429,  457.14285714,  525.        ,
        592.85714286,  660.71428571,  728.57142857,  796.42857143,
        864.28571429,  932.14285714, 1000.        ])

----

### NumPy array, bidimensional

In [34]:
list_of_lists = [[1,2,3],[4,5,6],[7,8,9]]
matrix = np.array(list_of_lists)

matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
list_of_lists[0][1] # access the matrix

2

In [36]:
type(list_of_lists)

list

In [37]:
type(matrix)

numpy.ndarray

In [38]:
matrix.shape

(3, 3)

In [39]:
matrix.size # number of elements

9

In [40]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
matrix[1][2]

6

In [42]:
submatrix = matrix[1:, :2] # matrix[row selection, column selection]
submatrix

array([[4, 5],
       [7, 8]])

In [43]:
submatrix2 = matrix[: : 2, : :2] # selection jumping in steps of 2
submatrix2

array([[1, 3],
       [7, 9]])

In [44]:
submatrix2.shape

(2, 2)

In [49]:
first_column = matrix[:,:1]
first_column

array([[1],
       [4],
       [7]])

In [45]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
# Selecting elements

matrix[matrix > 3]

array([4, 5, 6, 7, 8, 9])

### Generating multidimentional arrays

In [51]:
array15 = np.arange(15) # array from a range
array15 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [52]:
type(array15)

numpy.ndarray

In [53]:
array_jump = np.arange(1, 57, 5) # start, stop, jump
array_jump

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56])

In [54]:
array_jump.size

12

In [55]:
array_jump.reshape(3,4) # from an array to a 2d matrix

array([[ 1,  6, 11, 16],
       [21, 26, 31, 36],
       [41, 46, 51, 56]])

In [56]:
array_jump.reshape(3,2,2) # from an array to a 3d matrix

array([[[ 1,  6],
        [11, 16]],

       [[21, 26],
        [31, 36]],

       [[41, 46],
        [51, 56]]])

In [57]:
np.arange(1, 601, 3).size

200

In [58]:
bigger_matrix = np.arange(1, 601, 3).reshape(5,10,4) # 5x10x4 matrix
bigger_matrix

array([[[  1,   4,   7,  10],
        [ 13,  16,  19,  22],
        [ 25,  28,  31,  34],
        [ 37,  40,  43,  46],
        [ 49,  52,  55,  58],
        [ 61,  64,  67,  70],
        [ 73,  76,  79,  82],
        [ 85,  88,  91,  94],
        [ 97, 100, 103, 106],
        [109, 112, 115, 118]],

       [[121, 124, 127, 130],
        [133, 136, 139, 142],
        [145, 148, 151, 154],
        [157, 160, 163, 166],
        [169, 172, 175, 178],
        [181, 184, 187, 190],
        [193, 196, 199, 202],
        [205, 208, 211, 214],
        [217, 220, 223, 226],
        [229, 232, 235, 238]],

       [[241, 244, 247, 250],
        [253, 256, 259, 262],
        [265, 268, 271, 274],
        [277, 280, 283, 286],
        [289, 292, 295, 298],
        [301, 304, 307, 310],
        [313, 316, 319, 322],
        [325, 328, 331, 334],
        [337, 340, 343, 346],
        [349, 352, 355, 358]],

       [[361, 364, 367, 370],
        [373, 376, 379, 382],
        [385, 388, 391, 394],
    

In [59]:
bigger_matrix[4][0][0] # like access a list of a list of a list

481

In [60]:
bigger_matrix.dtype

dtype('int32')

---

In [61]:
# Identity matrix

id5 = np.identity(5) 
id5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [62]:
id5.ndim # dimention of the matrix

2

In [63]:
id5.shape # rows and columns

(5, 5)

In [64]:
id5.size # number of elements

25

In [65]:
id5.dtype # type of elements

dtype('float64')

---

In [66]:
# Matrix from random numbers, by default from 0 to (1 not included)

random_matrix = np.random.random((4,3)) # matrix 4x3 with random elements 
random_matrix

array([[0.12758736, 0.08755043, 0.73724992],
       [0.18770266, 0.12364267, 0.95211332],
       [0.11246688, 0.71253741, 0.8399751 ],
       [0.54591826, 0.69912582, 0.93059339]])

In [67]:
# Another way like help to recall documentation
?np.random.random

In [68]:
double = 2 * random_matrix # multiply with a scalar
double

array([[0.25517472, 0.17510086, 1.47449984],
       [0.37540532, 0.24728534, 1.90422665],
       [0.22493377, 1.42507483, 1.6799502 ],
       [1.09183652, 1.39825163, 1.86118679]])

In [69]:
double + random_matrix # sum element by element

array([[0.38276208, 0.2626513 , 2.21174976],
       [0.56310798, 0.37092801, 2.85633997],
       [0.33740065, 2.13761224, 2.51992529],
       [1.63775477, 2.09737745, 2.79178018]])

In [70]:
# We can round the randomly generated elements
mat4 = np.random.random((4,4))
mat4

array([[0.41379507, 0.88812867, 0.34501505, 0.07264214],
       [0.31071169, 0.01896022, 0.98632531, 0.60887699],
       [0.92342873, 0.13712306, 0.8990284 , 0.9019138 ],
       [0.34486409, 0.96497544, 0.78743067, 0.00842309]])

In [71]:
mat4_round = np.round(mat4, 2)
mat4_round

array([[0.41, 0.89, 0.35, 0.07],
       [0.31, 0.02, 0.99, 0.61],
       [0.92, 0.14, 0.9 , 0.9 ],
       [0.34, 0.96, 0.79, 0.01]])

In [72]:
np.sort(mat4_round)

array([[0.07, 0.35, 0.41, 0.89],
       [0.02, 0.31, 0.61, 0.99],
       [0.14, 0.9 , 0.9 , 0.92],
       [0.01, 0.34, 0.79, 0.96]])

In [73]:
# We can also generate random integers, here from 0 to 9 in a NumPy array (5,6)

np.random.randint(10,size=(5,6))

array([[5, 4, 6, 3, 6, 9],
       [4, 5, 9, 3, 2, 5],
       [5, 9, 7, 3, 0, 6],
       [0, 8, 4, 3, 6, 9],
       [7, 5, 9, 7, 9, 8]])

### Multiplication of matrices, with shape (a,b) * (b,a)

In [74]:
mat1 = np.mat([[1,2,3], [4,5,6]])
mat1

matrix([[1, 2, 3],
        [4, 5, 6]])

In [75]:
mat2 = np.mat([[0,21,3], [0,5,61]])
mat2

matrix([[ 0, 21,  3],
        [ 0,  5, 61]])

In [76]:
mat1.shape, mat2.shape

((2, 3), (2, 3))

In [77]:
# Let's transpose the second matrix to get the correct shape to perform a matrix multiplication
mat2t = mat2.T
mat2t

matrix([[ 0,  0],
        [21,  5],
        [ 3, 61]])

In [78]:
mat1.shape, mat2t.shape

((2, 3), (3, 2))

In [79]:
mat1

matrix([[1, 2, 3],
        [4, 5, 6]])

In [80]:
mat2t

matrix([[ 0,  0],
        [21,  5],
        [ 3, 61]])

In [81]:
# Matrix multiplication
mat1 * mat2t

matrix([[ 51, 193],
        [123, 391]])

If you instead want to multiply element by element, between matrices of the same shape, you can use `.multiply()`

In [82]:
molt_el = np.multiply(mat1, mat2)
molt_el

matrix([[  0,  42,   9],
        [  0,  25, 366]])

In [83]:
np.delete(molt_el,1,axis=0) # axis = 0 : row, delete row with index 1

matrix([[ 0, 42,  9]])

In [84]:
np.delete(molt_el,2,axis=1) # axis = 1 : column, delete column with index 2

matrix([[ 0, 42],
        [ 0, 25]])

To be sure you're doing matrix product you can also use `np.matmul()`  
https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.matmul.html

In [85]:
np.matmul(mat1, mat2t)

matrix([[ 51, 193],
        [123, 391]])

In [86]:
mat1 @ mat2t # dot product

matrix([[ 51, 193],
        [123, 391]])

### More linear algebra

Here you can find more on linear algebra  
https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.linalg.html

In [87]:
mat4

array([[0.41379507, 0.88812867, 0.34501505, 0.07264214],
       [0.31071169, 0.01896022, 0.98632531, 0.60887699],
       [0.92342873, 0.13712306, 0.8990284 , 0.9019138 ],
       [0.34486409, 0.96497544, 0.78743067, 0.00842309]])

In [88]:
# Diagonal
mat4.diagonal()

array([0.41379507, 0.01896022, 0.8990284 , 0.00842309])

In [89]:
# Compute the determinant
np.linalg.det(mat4)

-0.09612587447451129

In [90]:
# Compute the eigenvalues and right eigenvectors of a square array
np.linalg.eig(mat4)

(array([ 2.22918884+0.j       , -0.23484568+0.j       ,
        -0.32706819+0.2768439j, -0.32706819-0.2768439j]),
 array([[ 0.37033849+0.j        ,  0.2071398 +0.j        ,
          0.05627053-0.30511609j,  0.05627053+0.30511609j],
        [ 0.47009124+0.j        , -0.27946321+0.j        ,
          0.21806883+0.24423229j,  0.21806883-0.24423229j],
        [ 0.63595031+0.j        ,  0.49729744+0.j        ,
         -0.57946883+0.07164254j, -0.57946883-0.07164254j],
        [ 0.48726874+0.j        , -0.79478845+0.j        ,
          0.67499451+0.j        ,  0.67499451-0.j        ]]))

## Linear regression and polynomial fit

We can also perform linear regession with `numpy.polyfit()`  
https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.polyfit.html

In [91]:
x = np.array([-8,-2,3,4,5,6])
y = x * 2

fit_deg1 = np.polyfit(x, y, 1)
fit_deg1 # Polynomial coefficients

array([2.00000000e+00, 6.88316138e-16])

In [92]:
fit_deg2 = np.polyfit(x, y, 2)
fit_deg2

array([ 3.62799100e-16,  2.00000000e+00, -7.25194643e-15])

In [93]:
fit_deg3 = np.polyfit(x, y, 3)
fit_deg3

array([-3.42621768e-17, -1.24637441e-15,  2.00000000e+00,  3.84806407e-14])

---
### `>>> Let's practice` 
* Create an array of size 42 using arange 
* Convert it in a 2D matrix
* Select two rows in the middle
* Select only the elements bigger that 5
* Create two random matrix and muliply them

In [94]:
arr1 = np.arange(42)

In [154]:
arr1_ = np.linspace(0,42)

In [155]:
arr1_

array([ 0.        ,  0.85714286,  1.71428571,  2.57142857,  3.42857143,
        4.28571429,  5.14285714,  6.        ,  6.85714286,  7.71428571,
        8.57142857,  9.42857143, 10.28571429, 11.14285714, 12.        ,
       12.85714286, 13.71428571, 14.57142857, 15.42857143, 16.28571429,
       17.14285714, 18.        , 18.85714286, 19.71428571, 20.57142857,
       21.42857143, 22.28571429, 23.14285714, 24.        , 24.85714286,
       25.71428571, 26.57142857, 27.42857143, 28.28571429, 29.14285714,
       30.        , 30.85714286, 31.71428571, 32.57142857, 33.42857143,
       34.28571429, 35.14285714, 36.        , 36.85714286, 37.71428571,
       38.57142857, 39.42857143, 40.28571429, 41.14285714, 42.        ])

In [95]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41])

In [98]:
mtx = arr1.reshape(6,7)

In [102]:
mtx

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41]])

In [103]:
mtx[2:4,:]

array([[14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27]])

In [105]:
mtx[mtx>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
       40, 41])

In [114]:
mtx_ran1 = np.random.random((3,4))
mtx_ran1

array([[0.38211033, 0.32779301, 0.87570108, 0.55584897],
       [0.87308245, 0.65163309, 0.5343882 , 0.88228084],
       [0.38304572, 0.3272201 , 0.20096504, 0.39732625]])

In [117]:
mtx_ran2 = np.random.random((3,4))
mtx_ran2

array([[0.49216918, 0.91918998, 0.06984551, 0.94782925],
       [0.82161678, 0.63590216, 0.82592935, 0.76729251],
       [0.14412153, 0.69920833, 0.16776063, 0.41558943]])

In [148]:
mtx_ran1@mtx_ran2.T

array([[1.07738069, 1.67215853, 0.66217905],
       [1.90225509, 2.25004847, 1.03777316],
       [0.87993468, 0.99364514, 0.48283877]])

In [131]:
arr3 = [1,2,3,4,5,6]
mtx3 = np.array(arr3)
mtx3 = mtx3.reshape(3,2)

In [143]:
arr4 = [1,2,3,4,5,6]
mtx4 = np.array(arr3)
mtx4 = mtx4.reshape(2,3)

In [144]:
mtx3

array([[1, 2],
       [3, 4],
       [5, 6]])

In [145]:
mtx4

array([[1, 2, 3],
       [4, 5, 6]])

In [146]:
mtx3@mtx4

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])