# BIG DIVE Intesa 3
## Numpy
by Stefania Delprete, TOP-IX  
stefania.delprete@top-ix.org 

https://www.linkedin.com/in/astrastefania   
https://twitter.com/astrastefania  

---

## NumFOCUS

The mission of NumFOCUS, 501(c)3 non-profit organization, is to promote sustainable high-level programming languages, open code development, and reproducible scientific research.  
https://www.numfocus.org  
https://pydata.org

---

## NumPy

http://www.numpy.org   
https://github.com/numpy/numpy


In [1]:
import numpy as np

In [2]:
np.__version__

'1.14.3'

---
## Importing some maths

In [3]:
np.sqrt(144)

12.0

In [4]:
np.pi

3.141592653589793

In [5]:
np.sin(np.pi)

1.2246467991473532e-16

### NumPy array, unidimensional

In [6]:
heights_list = [175, 180, 168, 190, 175, 164, 189, 173, 171.23] # list
heights_np = np.array(heights_list) # NumPy array

In [7]:
heights_list, type(heights_list)

([175, 180, 168, 190, 175, 164, 189, 173, 171.23], list)

In [8]:
heights_list * 2

[175,
 180,
 168,
 190,
 175,
 164,
 189,
 173,
 171.23,
 175,
 180,
 168,
 190,
 175,
 164,
 189,
 173,
 171.23]

In [9]:
heights_np, type(heights_np)

(array([175.  , 180.  , 168.  , 190.  , 175.  , 164.  , 189.  , 173.  ,
        171.23]), numpy.ndarray)

In [10]:
heights_np * 2 # vector multiplication with a scalar

array([350.  , 360.  , 336.  , 380.  , 350.  , 328.  , 378.  , 346.  ,
       342.46])

In [11]:
heights_np / 2 # vector division with a scalar

array([87.5  , 90.   , 84.   , 95.   , 87.5  , 82.   , 94.5  , 86.5  ,
       85.615])

In [12]:
heights_np + 100

array([275.  , 280.  , 268.  , 290.  , 275.  , 264.  , 289.  , 273.  ,
       271.23])

In [13]:
np.sort(heights_np)

array([164.  , 168.  , 171.23, 173.  , 175.  , 175.  , 180.  , 189.  ,
       190.  ])

### Some statistics

In [14]:
mean = np.mean(heights_np)
mean

176.13666666666666

In [15]:
np.round(mean)

176.0

In [16]:
np.median(heights_np)

175.0

In [17]:
np.sum(heights_np)

1585.23

### Generating unidimentional arrays

In [18]:
np.zeros(9) # array of 9 zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
nine_ones = np.ones(9) # array of 9 ones
nine_ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [20]:
np.append(nine_ones,4) # add 4 at the end

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 4.])

In [21]:
np.insert(nine_ones,8,3.14) # insert at position 8, np.insert(np-array,index,value)

array([1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 3.14, 1.  ])

In [22]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [23]:
np.arange(0,15,3)

array([ 0,  3,  6,  9, 12])

In [24]:
rep_pattern = np.tile([3.14,42,2.99], 4) # repeating the pattern 4 times
rep_pattern

array([ 3.14, 42.  ,  2.99,  3.14, 42.  ,  2.99,  3.14, 42.  ,  2.99,
        3.14, 42.  ,  2.99])

In [25]:
np.unique([1,2,1,1,2]) # unique values

array([1, 2])

In [26]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [27]:
np.linspace(50, 1000, 15)

array([  50.        ,  117.85714286,  185.71428571,  253.57142857,
        321.42857143,  389.28571429,  457.14285714,  525.        ,
        592.85714286,  660.71428571,  728.57142857,  796.42857143,
        864.28571429,  932.14285714, 1000.        ])

----

### NumPy array, bidimensional

In [28]:
list_of_lists = [[1,2,3],[4,5,6],[7,8,9]]
matrix = np.array(list_of_lists)

matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
list_of_lists[0][1] # access the matrix

2

In [30]:
type(list_of_lists)

list

In [31]:
type(matrix)

numpy.ndarray

In [32]:
matrix.shape

(3, 3)

In [33]:
matrix.size # number of elements

9

In [34]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
matrix[1][2]

6

In [36]:
submatrix = matrix[1:, :2] # matrix[row selection, column selection]
submatrix

array([[4, 5],
       [7, 8]])

In [37]:
submatrix2 = matrix[: : 2, : :2] # selection jumping in steps of 2
submatrix2

array([[1, 3],
       [7, 9]])

In [38]:
submatrix2.shape

(2, 2)

In [39]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
# Selecting elements

matrix[matrix > 3]

array([4, 5, 6, 7, 8, 9])

### Generating multidimentional arrays

In [41]:
array15 = np.arange(15) # array from a range
array15 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [42]:
type(array15)

numpy.ndarray

In [43]:
array_jump = np.arange(1, 57, 5) # start, stop, jump
array_jump

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56])

In [44]:
array_jump.size

12

In [45]:
array_jump.reshape(3,4) # from an array to a 2d matrix

array([[ 1,  6, 11, 16],
       [21, 26, 31, 36],
       [41, 46, 51, 56]])

In [46]:
array_jump.reshape(3,2,2) # from an array to a 3d matrix

array([[[ 1,  6],
        [11, 16]],

       [[21, 26],
        [31, 36]],

       [[41, 46],
        [51, 56]]])

In [47]:
np.arange(1, 601, 3).size

200

In [48]:
bigger_matrix = np.arange(1, 601, 3).reshape(5,10,4) # 5x10x4 matrix
bigger_matrix

array([[[  1,   4,   7,  10],
        [ 13,  16,  19,  22],
        [ 25,  28,  31,  34],
        [ 37,  40,  43,  46],
        [ 49,  52,  55,  58],
        [ 61,  64,  67,  70],
        [ 73,  76,  79,  82],
        [ 85,  88,  91,  94],
        [ 97, 100, 103, 106],
        [109, 112, 115, 118]],

       [[121, 124, 127, 130],
        [133, 136, 139, 142],
        [145, 148, 151, 154],
        [157, 160, 163, 166],
        [169, 172, 175, 178],
        [181, 184, 187, 190],
        [193, 196, 199, 202],
        [205, 208, 211, 214],
        [217, 220, 223, 226],
        [229, 232, 235, 238]],

       [[241, 244, 247, 250],
        [253, 256, 259, 262],
        [265, 268, 271, 274],
        [277, 280, 283, 286],
        [289, 292, 295, 298],
        [301, 304, 307, 310],
        [313, 316, 319, 322],
        [325, 328, 331, 334],
        [337, 340, 343, 346],
        [349, 352, 355, 358]],

       [[361, 364, 367, 370],
        [373, 376, 379, 382],
        [385, 388, 391, 394],
    

In [49]:
bigger_matrix[4][0][0] # like access a list of a list of a list

481

In [50]:
bigger_matrix.dtype

dtype('int64')

---

In [51]:
# Identity matrix

id5 = np.identity(5) 
id5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [52]:
id5.ndim # dimention of the matrix

2

In [53]:
id5.shape # rows and columns

(5, 5)

In [54]:
id5.size # number of elements

25

In [55]:
id5.dtype # type of elements

dtype('float64')

---

In [56]:
# Matrix from random numbers, by default from 0 to (1 not included)

random_matrix = np.random.random((4,3)) # matrix 4x3 with random elements 
random_matrix

array([[0.02932468, 0.2360255 , 0.53889795],
       [0.82859233, 0.58181587, 0.33365308],
       [0.25012977, 0.36267549, 0.01573634],
       [0.40956249, 0.42056554, 0.46580311]])

In [57]:
# Another way like help to recall documentation
?np.random.random

In [58]:
double = 2 * random_matrix # multiply with a scalar
double

array([[0.05864937, 0.472051  , 1.0777959 ],
       [1.65718466, 1.16363174, 0.66730616],
       [0.50025954, 0.72535098, 0.03147268],
       [0.81912498, 0.84113107, 0.93160622]])

In [59]:
double + random_matrix # sum element by element

array([[0.08797405, 0.70807651, 1.61669385],
       [2.48577698, 1.74544761, 1.00095924],
       [0.75038931, 1.08802648, 0.04720902],
       [1.22868747, 1.26169661, 1.39740934]])

In [60]:
# We can round the randomly generated elements
mat4 = np.random.random((4,4))
mat4

array([[0.99688294, 0.72969063, 0.8600937 , 0.08406243],
       [0.00286871, 0.67367537, 0.9044493 , 0.40296564],
       [0.00977544, 0.49597287, 0.8353574 , 0.02723954],
       [0.23563506, 0.97399479, 0.29741491, 0.08118477]])

In [61]:
mat4_round = np.round(mat4, 2)
mat4_round

array([[1.  , 0.73, 0.86, 0.08],
       [0.  , 0.67, 0.9 , 0.4 ],
       [0.01, 0.5 , 0.84, 0.03],
       [0.24, 0.97, 0.3 , 0.08]])

In [62]:
np.sort(mat4_round)

array([[0.08, 0.73, 0.86, 1.  ],
       [0.  , 0.4 , 0.67, 0.9 ],
       [0.01, 0.03, 0.5 , 0.84],
       [0.08, 0.24, 0.3 , 0.97]])

In [63]:
# We can also generate random integers, here from 0 to 9 in a NumPy array (5,6)

np.random.randint(10,size=(5,6)) 

array([[1, 2, 8, 9, 7, 3],
       [6, 4, 7, 4, 8, 0],
       [2, 4, 3, 0, 1, 9],
       [0, 3, 2, 1, 6, 8],
       [2, 7, 5, 2, 2, 6]])

### Multiplication of matrices, with shape (a,b) * (b,a)

In [64]:
mat1 = np.mat([[1,2,3], [4,5,6]])
mat1

matrix([[1, 2, 3],
        [4, 5, 6]])

In [65]:
mat2 = np.mat([[0,21,3], [0,5,61]])
mat2

matrix([[ 0, 21,  3],
        [ 0,  5, 61]])

In [66]:
mat1.shape, mat2.shape

((2, 3), (2, 3))

In [67]:
# Let's transpose the second matrix to get the correct shape to perform a matrix multiplication
mat2t = mat2.T
mat2t

matrix([[ 0,  0],
        [21,  5],
        [ 3, 61]])

In [68]:
mat1.shape, mat2t.shape

((2, 3), (3, 2))

In [69]:
mat1

matrix([[1, 2, 3],
        [4, 5, 6]])

In [70]:
mat2t

matrix([[ 0,  0],
        [21,  5],
        [ 3, 61]])

In [71]:
# Matrix multiplication
mat1 * mat2t

matrix([[ 51, 193],
        [123, 391]])

If you instead want to multiply element by element, between matrices of the same shape, you can use `.multiply()`

In [72]:
molt_el = np.multiply(mat1, mat2)
molt_el

matrix([[  0,  42,   9],
        [  0,  25, 366]])

In [73]:
np.delete(molt_el,1,axis=0) # axis = 0 : row, delete row with index 1

matrix([[ 0, 42,  9]])

In [74]:
np.delete(molt_el,2,axis=1) # axis = 1 : column, delete column with index 2

matrix([[ 0, 42],
        [ 0, 25]])

To be sure you're doing matrix product you can also use `np.matmul()`  
https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.matmul.html

In [75]:
np.matmul(mat1, mat2t)

matrix([[ 51, 193],
        [123, 391]])

In [76]:
mat1 @ mat2t # dot product

matrix([[ 51, 193],
        [123, 391]])

### More linear algebra

Here you can find more on linear algebra  
https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.linalg.html

In [77]:
mat4

array([[0.99688294, 0.72969063, 0.8600937 , 0.08406243],
       [0.00286871, 0.67367537, 0.9044493 , 0.40296564],
       [0.00977544, 0.49597287, 0.8353574 , 0.02723954],
       [0.23563506, 0.97399479, 0.29741491, 0.08118477]])

In [78]:
# Diagonal
mat4.diagonal()

array([0.99688294, 0.67367537, 0.8353574 , 0.08118477])

In [79]:
# Compute the determinant
np.linalg.det(mat4)

-0.22325316148803312

In [80]:
# Compute the eigenvalues and right eigenvectors of a square array
np.linalg.eig(mat4)

(array([ 1.67751444, -0.37806281,  0.89380414,  0.39384472]),
 array([[ 0.78829537, -0.09195918,  0.97460087, -0.10842682],
        [ 0.39125204,  0.47910809, -0.04179873, -0.37178629],
        [ 0.25257811, -0.17589563, -0.1004709 ,  0.46901768],
        [ 0.40213997, -0.85502028,  0.19573352, -0.79375122]]))

## Linear regression and polynomial fit

We can also perform linear regession with `numpy.polyfit()`  
https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.polyfit.html

In [81]:
x = np.array([-8,-2,3,4,5,6])
y = x * 2

fit_deg1 = np.polyfit(x, y, 1)
fit_deg1 # Polynomial coefficients

array([ 2.00000000e+00, -7.25194643e-16])

In [82]:
fit_deg2 = np.polyfit(x, y, 2)
fit_deg2

array([ 2.17002687e-16,  2.00000000e+00, -3.24660246e-15])

In [83]:
fit_deg3 = np.polyfit(x, y, 3)
fit_deg3

array([-2.55131198e-18, -6.37781702e-16,  2.00000000e+00,  2.34302587e-14])

---
### `>>> Let's practice` 
* Create an array of size 42 using arange 
* Convert it in a 2D matrix
* Select two rows in the middle
* Select only the elements bigger that 5
* Create two random matrix and muliply them